name: vinhuni_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Mạng & API ---
  http: ^1.1.0

  # --- Giao diện & Tiện ích ---
  cupertino_icons: ^1.0.6
  flutter_widget_from_html_core: ^0.10.0
  flutter_markdown: ^0.6.14
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

  # --- Firebase & Thông báo ---
  # Lưu ý: Các phiên bản này được chọn để tương thích tốt nhất với nhau
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  
  # QUAN TRỌNG: Dùng bản 17.x để không bị lỗi "Too many positional arguments"
  flutter_local_notifications: ^17.2.3 
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  device_info_plus: ^10.1.0

flutter:
  uses-material-design: true

  # Cấu hình ảnh (Đảm bảo bạn đã tạo thư mục assets/images ngang hàng với lib)
  assets:
    - assets/images/